spring:
  profiles:
    active: work  
  data:
    redis:
      host: localhost
      port: 6380

  jackson:
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: ${dashscope.api-key}
        model-name: qwen-plus
        temperature: 0.7
      streaming-chat-model:
          api-key: ${dashscope.api-key}
          model-name: qwen-plus
          temperature: 0.7
      embedding-model:
        api-key: ${dashscope.api-key}
        model-name: text-embedding-v4

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  secret: 2956195122zzzjjjwww2956195122zzzjjjwww
  expire-hours: 720
  header: Authorization

sms:
  code-expire-minutes: 5
  code-length: 6

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  compression:
    enabled: false

bigmodel:
  api-key: ${bigmodel.api-key}


